### ISSUE TITLE
🔨 [Chore] nestjs 개발 환경 설정 

### ISSUE THREAD

**Issue by joosomi** [joosomi/bookpecker#1]
### 참고) 필수 기술 스택

1. Node.js 18.18.x
2. NestJS 9.5.x
3. TypeScript 5.1.x
4. PostgreSQL 15.7.x
5. Prisma 5.18.x

###  기본 프로젝트 구조
```
src/
├── feature/
│   ├── common/
│   │   ├── book-search/
│   │   └── ...
│   ├── graphql/
│   │   ├── book/
│   │   └── note/
│   └── rest/
│       ├── oauth/
│       └── ...
├── prisma/
├── app.module.ts
├── graphql.ts
└── main.ts
```

## ✅ TODO

- [x] NestJS 프로젝트 세팅 : 기본 프로젝트 구조 생성
- [x] 환경 변수 파일 (`.env`) 설정  -> `.env.sample` 필요 
- [x] Docker 설정 
   - [x] (node 18.18.x alpine, postgreSQL)
   - [x] docker-compose.dev.yml: 개발 환경용
   - [ ] docker-compose.prod.yml: 추후 프로덕션 환경용 
- [x] ESLint 및 Prettier 설정
- [x] 로깅 및 에러 핸들링 - winston ,전역 exception filter 
   - [ ] logging interceptor (현재는 error 만 로깅하고 있음. interceptor 사용시 모든 요청/응답 로깅 가능)
- [x] swagger 설정

#### prisma에 대해 알아보기
https://www.prisma.io/blog/nestjs-prisma-rest-api-7D056s1BmOL0
자동 마이그레이션 제공 - 빠른 개발이 가능
Prisma의 자동 생성된 타입은 GraphQL 스키마 정의와 쉽게 매핑

```
npx prisma studio
```
쉽게 db 값들을 볼 수 있음 
#### docker compose 백그라운드 실행 명령어
```
docker-compose -f docker-compose.dev.yml up -d
```

#### 배포 -  env.prod.sample 필요
