### ISSUE TITLE
✨ [Feature] 카카오 소셜 로그인

### ISSUE THREAD

**Issue by joosomi** [joosomi/bookpecker#5]
## 🚀 Description
KAKAO OAuth2를 사용하여 로그인 기능 구현하기 
사용자 카카오 프로필 정보를 가져와서 사용자 DB에 저장

#### Authentication
- 카카오 소셜 회원가입/로그인 기능 (REST)

## ✅ TODO
- [x] 카카오 로그인 구현
  - [x] 카카오 인증 redirect `GET /api/auth/kakao`
- [x] JWT 전역 인증 Guard 
- [x] unit 테스트 코드 
- [ ] 소셜 로그인 통합 테스트 코드 
- [ ] Postman [참고](https://rhdqors.tistory.com/39)
- [ ] swagger 

## 📢 Notes
[카카오 로그인 공식 문서](https://developers.kakao.com/docs/latest/ko/kakaologin/rest-api#req-user-info)

#### Passport Kakao Strategy 
카카오 OAuth 인증을 직접 서비스단(카카오 토큰 발급 요청, 사용자 정보 가져오기, jwt Access Token 발급 등)에서 모두 구현했었는데, 
passport kakao를 활용하면 엄청 간단하게 구현이 가능하다는 것을 알 수 있었다.
passport를 적극 활용하자.. 

<details>
    <summary>이전 코드</summary>

```javascript
   // async kakaoLogin(code: string): Promise<{ accessToken: string }> {
    //   //1. 카카오 액세스 토큰 발급
    //   const kakaoToken = await this.getKakaoToken(code);
  
    //   // 2. 토큰을 사용하여 사용자 정보 가져오기
    //   const userData = await this.getKakaoUserInfo(kakaoToken);
  
    //   const kakaoId = userData.id;
  
    //   // 카카오 아이디(unique)로 사용자 검색
    //   let user = await this.prisma.user.findUnique({
    //     where: { kakaoId: kakaoId.toString() },
    //   });
  
    //   // 사용자가 없으면 새로 생성
    //   if (!user) {
    //     user = await this.prisma.user.create({
    //       data: {
    //         kakaoId: kakaoId.toString(),
    //         email: userData.kakao_account.email,
    //         username: userData.kakao_account.profile.nickname,
    //       },
    //     });
    //   }
  
    //   //jwt accessToken 생성
    //   const payload = { sub: user.id, email: user.email, username: user.username };
    //   const accessToken = this.jwtService.sign(payload);
  
    //   return { accessToken };
    // }
  
    // /**
    //  *  카카오 액세스 토큰 발급 요청
    //  * @param code
    //  * @returns kakaoToken
    //  */
    // private async getKakaoToken(code: string): Promise<string> {
    //   const clientId = this.configService.get<string>('KAKAO_CLIENT_ID');
    //   const redirectUri = this.configService.get<string>('KAKAO_REDIRECT_URI');
  
    //   try {
    //     const { data } = await axios.post('https://kauth.kakao.com/oauth/token', null, {
    //       params: {
    //         grant_type: 'authorization_code',
    //         client_id: clientId,
    //         redirect_uri: redirectUri,
    //         code,
    //       },
    //     });
  
    //     const kakaoToken = data.access_token;
    //     return kakaoToken;
    //   } catch (err) {
    //     throw new UnauthorizedException('카카오 액세스 토큰 발급에 실패했습니다.');
    //   }
    // }
  
    // /**
    //  * 카카오 토큰으로 사용자 정보 가져오기
    //  * @param kakaoToken
    //  * @returns <KakaoUserData> : id, email, nickname
    //  */
    // private async getKakaoUserInfo(kakaoToken: string): Promise<KakaoUserData> {
    //   try {
    //     const { data } = await axios.get<KakaoUserData>('https://kapi.kakao.com/v2/user/me', {
    //       headers: { Authorization: `Bearer ${kakaoToken}` },
    //     });
    //     return data;
    //   } catch (err) {
    //     throw new UnauthorizedException('카카오 사용자 정보를 가져오는데 실패했습니다.');
    //   }
    // }
```
</details>

------

#### NestJS에서의 테스팅
- 단위 테스트 (Unit Testing): 애플리케이션의 가장 작은 단위(주로 함수나 메소드)를 독립적으로 테스트
- 통합 테스트 (Integration Testing): 여러 모듈이나 서비스가 함께 정상적으로 작동하는지 검증
- e2e 테스트 (End-to-End Testing): 사용자의 관점에서 애플리케이션의 흐름을 테스트하여 전체 시스템의 기능을 검증
