### ISSUE TITLE
✨ [Feature] Book 기능 구현 - 책 검색, 저장, 좋아요 및 외부 공유 기능

### ISSUE THREAD

**Issue by joosomi** [joosomi/bookpecker#6]
## 🚀 Description

로그인한 사용자는 아래의 기능을 사용할 수 있습니다. 
1. 책 검색 및 저장 기능 
    - 책 검색: [Naver 책 검색 API](https://developers.naver.com/docs/serviceapi/search/book/book.md) 사용 (REST)
            <img width="599" alt="스크린샷 2024-09-25 오후 8 09 28" src="https://github.com/user-attachments/assets/4a533ce0-31da-4456-8cf0-bdc3371721ac">

    - 검색된 책 중 사용자가 선택한 책 DB 저장 (GraphQL)
2. 저장한 책 좋아요 기능 (GraphQL)
3. 저장한 책 정보 외부 공유 기능 (REST)
    - JWT 토큰 사용(열람 만료 기한은 공유 시점으로부터 10분)
    - 타 사용자/비로그인 사용자)
      -  공유자가 저장한 책 정보 및 해당 책에 공유자가 작성한 노트 열람이 가능
  
        
## ✅ TODO

- [x] 책 검색 
  - [x] Books Table 컬럼 추가(`link`) (prisma schema, migration)
- [x] 책 저장 
- [x] 저장한 책 좋아요
- [x] 공유용 토큰 생성/ 외부 공유 기능
- [x] schema first 방식으로 refactoring
- [ ] Postman
- [ ] 테스트 코드
- [ ] swagger
- [ ] 에러 처리 확인 

## 📢 Notes
- #### Naver 책 검색 API 예시 응답
  ```
    {
                "title": "계수나무 줄기에 딱따구리 집 (스토리에 색을 입히는 컬러링북 & 판타지 그림책)",
                "link": "https://search.shopping.naver.com/book/catalog/32484729652",
                "image": "https://shopping-phinf.pstatic.net/main_3248472/32484729652.20221229074711.jpg",
                "author": "우덕현",
                "discount": "13500",
                "publisher": "다할미디어",
                "pubdate": "20160330",
                "isbn": "9791186306543",
                "description": "거문고와 불로장생 묘약 이야기의 절묘한 만남\n전 연령대가 즐길 수 있는 힐링 동화\n\n『계수나무 ...        
    },
  ```

    `pubdate` yyyymmdd string, `discount`도 string 받아옴. 
     가격 정보는 저장을 안할테니 상관없지만, `pubdate`는 저장할 때 Date로 변환 필요
    
    `isbn` 저장할 때 string, number로 할지 고민
     : ISBN은 때때로 0으로 싲가할 수 있기 때문에 string이 맞다고 판단. string으로 하면 변환없이 그대로 사용 가능. 

- #### UserBook Table의 필요성
  : User와 Book 사이의 관계 저장 , 현재는 좋아요(`isLiked`) 컬럼만 있지만, 추후 확장 가능(readStatus 라든지 추가 가능)

- #### 공유용 토큰 관리 필요성
   - 왜? 토큰 무효화 및 토큰 재사용 방지 및 토큰 사용 추적을 위함
   : 추후 공유용 토큰 관리를 위한 redis 연결 필요

- #### graphQL 공부하기 
     [NestJS docs](https://docs.nestjs.com/graphql/quick-start)

- **외부 공유 기능에서 JWT 토큰을 사용한 접근 권한 관리 및 만료 시간 설정(10분) 어떻게 구현할 것인가?**
  - sharing 용 custom guard를 따로 구현해야하는 것일까?
  - 서비스 단에서 검증을 해도 될 것 같다. 
  - 이유: 비로그인한 사람들도 접근 가능한 엔드포인트 이기 때문에 가드를 구현하면 오히려 복잡해질 것 같다.
  - service단에서 토큰을 검증하는 것이 오히려 단순
  - 하지만 추후 외부 공유할 때 여러 종류의 토큰이 생기게 된다거나, 공유 토큰을 사용하는 여러 엔드포인트가 있다거나 그러면 고려 가능
  - 현재는 외부 공유 엔드포인트는 1개 뿐이라 서비스 단에서 구현하기로 결정 

#### GraphQL Code-first -> Schema-first 방식 리팩토링
: Code-first 는 타입 안정성이 높은 반면, Schema-first는 스키마가 독립적으로 관리, 스키마 중심의 개발이 가능. 

- Code-First 방식
  - TypeScript 데코레이터(@ObjectType, @Field, @InputType 등)를 사용하여 GraphQL 타입과 스키마를 코드 내에서 정의합니다.
  - NestJS가 데코레이터를 기반으로 GraphQL 스키마를 자동으로 생성

- Schema-First 방식
  - .graphql 파일 등 외부 스키마 정의 파일을 먼저 작성합니다.
  - NestJS는 이 스키마 파일을 읽고, 해당 스키마에 맞춰 리졸버와 타입을 구현합니다.
  - 스키마 중심의 개발이 가능하며, 비개발자도 스키마 파일을 통해 API 구조를 쉽게 이해할 수 있습니다.
