### ISSUE TITLE
  📝 [Docs] API 명세서 작성 및 문서화 작업

### ISSUE THREAD

**Issue by joosomi** [joosomi/bookpecker#9]
## 🚀 Description
API 테스트 Postman 

## ✅ TODO

- [ ] Postman 문서화 및 테스트
- [ ] Swagger / GraphQL playground
- [ ] README 작성 (README에 구현 사항을 체크하고 기록 남기기)
